
name: Columbus CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  POSTGRES_HOST: localhost    

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11"]

  services:
    # Label used to access the service container
    postgres:
      # Docker Hub image
      image: postgres
      # Provide the password for postgres
      env:
        POSTGRES_PASSWORD: postgres
      # Set health checks to wait until postgres has started
      ports:
        - 5432:5432
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black flake8 pytest pytest-mock mypy isort httpx sqlalchemy-utils
        python3 -m pip install types-PyYAML
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi   
    - name: Sort imports   
      run: |
        isort columbus 
    - name: Format with Black
      run: |
        black columbus 
    - name: Run tests
      run: |
        python -m  pytest -s tests
      env: 
        # The hostname used to communicate with the PostgreSQL service container
        POSTGRES_HOST: postgres
        # The default PostgreSQL port
        POSTGRES_PORT: 5432